baseURL = "https://go-pro-world.net/"
languageCode = "ja"
title = "Go out into PG world"
theme = "paige"
defaultContentLanguage = "ja"
enableRobotsTXT = true

# ページネーション
[pagination]
  pagerSize = 10

# サイト情報
[params]
  author = "Hisao"
  description = "Zenn記事とGitHubプロジェクトをまとめたポートフォリオ"
  customCSS = ["css/custom.scss"]
  
# ソーシャルリンク
[[params.social]]
  name = "github"
  url  = "https://github.com/hisao5232"

[[params.social]]
  name = "zenn"
  url  = "https://zenn.dev/hisao5232"

[[params.social]]
  name = "twitter"
  url  = "https://x.com/<your-twitter-handle>"

# Markdown内の生HTMLを安全に表示する設定
[markup]
  [markup.goldmark.renderer]
    unsafe = true
